disappear_times = {
    "pet şişe": "400 - 450 yıl",
    "cam şişe": "4000 - 5000 yıl",
    "plastik torba": "100 - 1000 yıl",
    "kağıt": "2 - 5 ay",
    "gazete": "6 hafta",
    "karton": "2 ay",
    "biyolojik atık": "1 - 6 ay",
    "muz kabuğu": "2 - 5 hafta",
    "elma çekirdeği": "2 ay",
    "portakal kabuğu": "6 ay",
    "sigara izmariti": "10 - 15 yıl",
    "sakız": "5 yıl",
    "alüminyum kutu": "200 - 500 yıl",
    "teneke kutu": "50 yıl",
    "strafor köpük": "500+ yıl",
    "plastik pipet": "200 yıl",
    "plastik kapak": "400 yıl",
    "plastik çatal": "400 yıl",
    "plastik tabak": "400 yıl",
    "plastik bardak": "50 yıl",
    "diş fırçası": "500 yıl",
    "bebek bezi": "450 - 500 yıl",
    "islak mendil": "100 yıl",
    "maske cerrahi": "400 yıl",
    "pil": "300 yıl",
    "telefon bataryası": "500 yıl",
    "lastik araba": "100 - 200 yıl",
    "ayakkabı spor": "30 - 40 yıl",
    "deri ayakkabı": "25 - 40 yıl",
    "pamuklu tişört": "5 ay",
    "yün çorap": "1 - 5 yıl",
    "naylon kumaş": "30 - 40 yıl",
    "balık ağı naylon": "600 yıl",
    "olta misinası": "600 yıl",
    "ahşap parçası": "10 - 15 yıl",
    "kontrplak": "1 - 3 yıl",
    "sigara paketi": "5 yıl",
    "süt kartonu": "5 yıl",
    "meyve suyu kutusu": "5 yıl",
    "dergi": "1 yıl",
    "tuvalet kağıdı": "2 - 4 hafta",
    "kağıt havlu": "2 - 4 hafta",
    "saç teli": "1 - 2 yıl",
    "tırnak": "1 yıl",
    "kemik": "1 - 5 yıl",
    "yumurta kabuğu": "1 yıl",
    "çay poşeti": "3 - 6 ay",
    "kahve telvesi": "2 - 3 ay",
    "ekmek": "2 - 3 hafta",
    "sebze atıkları": "1 - 2 ay"
}